473 order by amount of hearts user has allocated
lexicongovernance/pluraltools-frontend pull request #482
Opened 2024-05-16 05:58 UTC by camilovegag

## Closes: #473

## Evidence:
![image](https://github.com/lexicongovernance/pluraltools-frontend/assets/59750365/8556be97-d0a6-4717-a7b1-df61b7902b0c)

2024-05-16 06:53 UTC, diegoalzate requested changes

2024-05-16 06:53 UTC, diegoalzate commented on packages/berlin/src/pages/Cycle.tsx
> +    column: 'numOfVotes',
i dont like how this ordering affects my voting without it actually saving. Is there a way to order this only after saving?

2024-05-16 15:42 UTC, diegoalzate commented
@camilovegag on initial load i get this:
![CleanShot 2024-05-16 at 16 42 12@2x](https://github.com/lexicongovernance/pluraltools-frontend/assets/22416585/f92ef508-061a-4ddf-8701-77fe0f9e3078)

2024-05-17 04:09 UTC, camilovegag commented
Working on this, harder than it looks

2024-05-17 13:52 UTC, diegoalzate approved these changes

2024-05-17 13:52 UTC, merged